/obj/item/weapon/storage/lightbulbs/New()
	..()
	new /obj/item/weapon/bulb/incandescent( src )
	new /obj/item/weapon/bulb/incandescent( src )
	new /obj/item/weapon/bulb/incandescent( src )
	new /obj/item/weapon/bulb/incandescent( src )
	new /obj/item/weapon/bulb/incandescent( src )
	new /obj/item/weapon/bulb/incandescent( src )
	new /obj/item/weapon/bulb/incandescent( src )

/obj/item/weapon/storage/fluorescentbulbs/New()
	..()
	new /obj/item/weapon/bulb( src )
	new /obj/item/weapon/bulb( src )
	new /obj/item/weapon/bulb( src )
	new /obj/item/weapon/bulb( src )
	new /obj/item/weapon/bulb( src )
	new /obj/item/weapon/bulb( src )
	new /obj/item/weapon/bulb( src )