/obj/item/weapon/geneticsanalyzer/attack(mob/M as mob, mob/user as mob)
	for(var/mob/O in viewers(M, null))
		O.show_message(text("\red [] has analyzed []'s genetic code!", user, M), 1)
		//Foreach goto(67)
	user.show_message(text("\blue Analyzing Results for [M]: [M.primarynew.struc_enzyme]\n\t"), 1)
	user.show_message(text("\blue \t Bad Vision: [isblockon(getblock(M.primarynew.struc_enzyme, BAD_VISION,3),BAD_VISION ? "Yes" : "No")]"), 1)
	user.show_message(text("\blue \t Unknown: [isblockon(getblock(M.primarynew.struc_enzyme, HULK,3),HULK) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Epilepsy: [isblockon(getblock(M.primarynew.struc_enzyme, HEADACHE,3),HEADACHE) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Stumble: [isblockon(getblock(M.primarynew.struc_enzyme, STRANGE,3),STRANGE) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Cough: [isblockon(getblock(M.primarynew.struc_enzyme, COUGH,3),COUGH) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Clumsy: [isblockon(getblock(M.primarynew.struc_enzyme, LIGHTHEADED,3),LIGHTHEADED) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Twitch: [isblockon(getblock(M.primarynew.struc_enzyme, TWITCH,3),TWITCH) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Unknown: [isblockon(getblock(M.primarynew.struc_enzyme, XRAY,3),XRAY) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Nervous: [isblockon(getblock(M.primarynew.struc_enzyme, NERVOUS,3),NERVOUS) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Unknown: [isblockon(getblock(M.primarynew.struc_enzyme, AURA,3),AURA) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Blind: [isblockon(getblock(M.primarynew.struc_enzyme, ISBLIND,3),ISBLIND) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Unknown: [isblockon(getblock(M.primarynew.struc_enzyme, TELEKINESIS,3),TELEKINESIS) ? "Yes" : "No"]"), 1)
	user.show_message(text("\blue \t Deaf: [isblockon(getblock(M.primarynew.struc_enzyme, DEAF,3),DEAF) ? "Yes" : "No"]"), 1)
	return